### ISSUE TITLE
Allow scoping unstable features to specific targets

### ISSUE THREAD

**Issue by ketsuban** [rust-lang/wg-cargo-std-aware#89]
Currently if I want to use `build-std` in my `.cargo/config.toml` file I have to put it in an `[unstable]` section which applies it for every target when I only want to build the standard library for one. Would it be possible to do something like this, so that the unstable flags are only added when building for the appropriate target?

```toml
[target.thumbv4t-none-eabi]
runner = "mGBA"
rustflags = ["-Clink-arg=-Tlinker.ld"]

[target.thumbv4t-none-eabi.unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-weak-intrinsics"]
```
